-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.islemler (
  id bigint NOT NULL DEFAULT nextval('islemler_id_seq'::regclass),
  uuid uuid DEFAULT gen_random_uuid() UNIQUE,
  symbol text NOT NULL,
  karar USER-DEFINED NOT NULL,
  durum USER-DEFINED NOT NULL DEFAULT 'AKTIF'::islem_durumu,
  long_oran numeric,
  short_oran numeric,
  risk_skor smallint CHECK (risk_skor >= 1 AND risk_skor <= 10),
  guven smallint CHECK (guven >= 0 AND guven <= 100),
  giris_fiyati numeric NOT NULL,
  stop_loss numeric,
  take_profit_1 numeric,
  take_profit_2 numeric,
  cikis_fiyati numeric,
  kapanma_nedeni USER-DEFINED,
  pozisyon_usdt numeric,
  kaldirac smallint DEFAULT 1,
  pnl_yuzde numeric,
  pnl_usdt numeric,
  sure_dakika integer,
  acilis_zamani timestamp with time zone NOT NULL DEFAULT now(),
  kapanis_zamani timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  binance_order_id text,
  binance_durum text DEFAULT 'BEKLIYOR'::text,
  tp_algo_id text,
  sl_algo_id text,
  CONSTRAINT islemler_pkey PRIMARY KEY (id)
);
CREATE TABLE public.liquidations (
  id bigint NOT NULL DEFAULT nextval('liquidations_id_seq'::regclass),
  symbol text NOT NULL,
  side text NOT NULL CHECK (side = ANY (ARRAY['LONG'::text, 'SHORT'::text])),
  order_type text,
  time_in_force text,
  quantity numeric NOT NULL,
  price numeric NOT NULL,
  avg_price numeric,
  status text,
  usd_value numeric NOT NULL,
  trade_time timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT liquidations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.market_snapshots (
  id bigint NOT NULL DEFAULT nextval('market_snapshots_id_seq'::regclass),
  ts timestamp with time zone NOT NULL,
  symbol text NOT NULL,
  price numeric,
  price_change_1h_pct numeric,
  price_change_4h_pct numeric,
  long_pct numeric,
  short_pct numeric,
  ls_ratio numeric,
  top_trader_long_pct numeric,
  top_trader_short_pct numeric,
  top_trader_ls_ratio numeric,
  funding_rate numeric,
  oi_usd numeric,
  volume_24h numeric,
  volume_24h_change_pct numeric,
  bid_total numeric,
  ask_total numeric,
  ba_ratio numeric,
  vwap_bid numeric,
  vwap_ask numeric,
  mark_index_diff numeric,
  CONSTRAINT market_snapshots_pkey PRIMARY KEY (id)
);